package mage.client.dialog;

import java.awt.*;
import mage.client.MageFrame;
import mage.utils.MageVersion;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 * App GUI: about window
 *
 * @author JayDi85
 */
public class AboutDialog extends MageDialog {

    private static String devsList = "BetaSteward, Noxx, Eugen.Rivniy, North, LevelX2, "
            + "Jeff, Plopman, dustinconrad, emerald000, fireshoes, lunaskyrise, "
            + "mnapoleon, jgod, LoneFox, drmDev, spjspj, TheElk801, L_J, JayDi85, "
            + "jmharmon, Ketsuban, hitch17, weirddan455";

    public AboutDialog() {
        initComponents();
        this.modal = false;
        panelDevs.setText(devsList + " and hundreds of other developers from https://github.com/magefree/mage/graphs/contributors");
    }

    public void showDialog(MageVersion version) {
        this.lblVersion.setText(version.toString());
        this.setLocation(100, 100);

        // windows settings
        MageFrame.getDesktop().remove(this);
        if (this.isModal()) {
            MageFrame.getDesktop().add(this, JLayeredPane.MODAL_LAYER);
        } else {
            MageFrame.getDesktop().add(this, JLayeredPane.PALETTE_LAYER);
        }
        this.makeWindowCentered();

        // Close on "ESC"
        registerKeyboardAction(e -> onCancel(), KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        this.setVisible(true);
    }

    private void onCancel() {
        this.hideDialog();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnOk = new JButton();
        jLabel1 = new JLabel();
        lblVersion = new JLabel();
        jLabel2 = new JLabel();
        btnWhatsNew = new JButton();
        scrollDevs = new JScrollPane();
        panelDevs = new JTextPane();
        labelDevs = new JLabel();
        textPane1 = new JTextPane();

        //======== this ========
        setVisible(true);
        setMaximizable(true);
        setTitle("About XMage");
        Container contentPane = getContentPane();

        //---- btnOk ----
        btnOk.setText("Close");
        btnOk.addActionListener(e -> btnOkActionPerformed(e));

        //---- jLabel1 ----
        jLabel1.setText("XMage client");

        //---- lblVersion ----
        lblVersion.setText("0.0.0");

        //---- jLabel2 ----
        jLabel2.setText("Courtesy: BetaSteward@googlemail.com. Site: http://xmage.cn/");

        //---- btnWhatsNew ----
        btnWhatsNew.setText("What's new");
        btnWhatsNew.addActionListener(e -> btnWhatsNewActionPerformed(e));

        //======== scrollDevs ========
        {
            scrollDevs.setBorder(null);

            //---- panelDevs ----
            panelDevs.setEditable(false);
            scrollDevs.setViewportView(panelDevs);
        }

        //---- labelDevs ----
        labelDevs.setText("Developers:");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(scrollDevs)
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addComponent(btnWhatsNew, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOk, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblVersion))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(jLabel2)
                                        .addComponent(labelDevs))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 67, Short.MAX_VALUE)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblVersion))
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelDevs)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scrollDevs, GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(btnOk, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnWhatsNew, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(textPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        onCancel();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnWhatsNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatsNewActionPerformed
        MageFrame.showWhatsNewDialog();
    }//GEN-LAST:event_btnWhatsNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnOk;
    private JLabel jLabel1;
    private JLabel lblVersion;
    private JLabel jLabel2;
    private JButton btnWhatsNew;
    private JScrollPane scrollDevs;
    private JTextPane panelDevs;
    private JLabel labelDevs;
    private JTextPane textPane1;
    // End of variables declaration//GEN-END:variables

}
